#!/usr/bin/env bash
#
# A synchronization barrier for your shell.
#
# Usage:
#   barrier [<count>|<hosts>...]
#
# Options:
#   count    The number of notifications to wait for [default: 1]
#   hosts    Hostname to notify that the barrier has been reached
#
# @example
# Wait for a single notification before proceeding:
#
# ```
# barrier
# ```
#
# @example
# Wait for 3 notifications before proceeding:
#
# ```
# barrier 3
# ```
#
# @example
# Notify localhost without blocking:
#
# ```
# barrier localhost
# ```
#
# @example
# Notify host1 and host2 without blocking:
#
# ```
# barrier host1 host2
# ```

set -o errexit
set -o nounset
set -o pipefail

readonly default_port=64926
readonly port="${PORT:-${default_port}}"

printHelp() {
    cat <<-EOF

Usage:
  barrier [<count>|<hosts>...]

Options:
  count    The number of broadcasts to wait for [default: 1]
  hosts    Hostname to notify that the barrier has been reached

EOF
    exit 1
}

listen() {
  # shellcheck disable=SC2034
  for i in $(seq 1 "$1"); do
    nc -l "${port}"
  done
}

broadcast() {
  for host in "$@"; do
    echo | nc -N "${host}" "${port}"
  done
}

main() {
  while true; do
    case "${1:-}" in
      -h|--help) printHelp ;;
      --) shift; break ;;
      *) break ;;
    esac
  done

  if [[ "$#" -eq 0 ]]; then
    listen 1
  elif [[ $1 =~ ^-?[0-9]+$ ]]; then
    listen "${1:-}"
  else
    broadcast "$@"
  fi
}

main "$@"
